// src/constants/routeConstants.js
export const ROUTE_PATHS = {
  HOME: "/",
  MAIN: "/main",
  SIGNUP: "/signup",
  LOGIN: "/login",
  APPLY: "/apply",
  SELECT: "/select",
  ABOUT: "/about",
  CONTACT: "/contact",
  HISTORY:"/history",
  HISTORYDETAIL:"/history_detail",
  HISTORYMY:"/history_upload",
  RECAP:"/recap",
  HOMECHECK:"/home_check",
  HOMECHECKFIX:"/home_check_fix",
  HOMEWRITE:"/home_write",
  HOMEWRITEFIX:"/home_write_fix",
  SPLASH:"/splash",
  MYPAGE:"/mypage",
  ONBOARDING:"/onboarding",
  NOT_FOUND: "*",
};
